### ISSUE TITLE
Battle task crash (possibly related to Wild Weed removal?)

### ISSUE THREAD

**Issue by RedEnchilada** [silverweed/pokepon#4]
Screenshot of server at the time of crash: http://i.imgur.com/lLN3HOD.png

Seems to be a threading issue and a needed synchronized() block somewhere.

**Comment by silverweed** [comment]
Should be fixed: https://github.com/silverweed/pokepon/commit/8e0cd2a24fb8419445980d7015324f3b430425e5, closing for now
